// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmwbaOkuQkY6UG0nlrlsMyQlmPvqTriP0',
    appId: '1:998290823848:web:a2e19c5cf7001ba7b0c09d',
    messagingSenderId: '998290823848',
    projectId: 'animinfo-84786',
    authDomain: 'animinfo-84786.firebaseapp.com',
    storageBucket: 'animinfo-84786.firebasestorage.app',
    measurementId: 'G-TXBEJL2TCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS1JLyBH20O51ukVVShdfnxhYQFYykpKc',
    appId: '1:998290823848:android:f9c5caf90ceee794b0c09d',
    messagingSenderId: '998290823848',
    projectId: 'animinfo-84786',
    storageBucket: 'animinfo-84786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4mmpv3YWr9CiyYPnePc8RrRglJiqL5zo',
    appId: '1:998290823848:ios:561a941bf68b2822b0c09d',
    messagingSenderId: '998290823848',
    projectId: 'animinfo-84786',
    storageBucket: 'animinfo-84786.firebasestorage.app',
    iosBundleId: 'com.example.apiAnime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4mmpv3YWr9CiyYPnePc8RrRglJiqL5zo',
    appId: '1:998290823848:ios:561a941bf68b2822b0c09d',
    messagingSenderId: '998290823848',
    projectId: 'animinfo-84786',
    storageBucket: 'animinfo-84786.firebasestorage.app',
    iosBundleId: 'com.example.apiAnime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmwbaOkuQkY6UG0nlrlsMyQlmPvqTriP0',
    appId: '1:998290823848:web:dcc2de1302605d4bb0c09d',
    messagingSenderId: '998290823848',
    projectId: 'animinfo-84786',
    authDomain: 'animinfo-84786.firebaseapp.com',
    storageBucket: 'animinfo-84786.firebasestorage.app',
    measurementId: 'G-PD32N6V0F5',
  );
}
